column_width = 100
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
line_endings = "Unix"
no_call_parentheses = false
collapse_simple_statement = "Never" 